version: '3.8'

services:
  hardhat:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # Mount your local directory to /app/local for file sharing
      - ./:/app/local
    # Keep the container running
    command: tail -f /dev/null
    # Optional: expose ports if your Hardhat setup needs them
    ports:
      - "8545:8545"  # Default Hardhat network port
